app:
  name: lab-service
  image: nginxinc/nginx-unprivileged
  tag: alpine
  pullPolicy: Always
  replicaCount: 1
  port: 8080
  env: "lab"
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    capabilities:
      drop:
        - ALL
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
    fsGroup: 1031 # take this out if deploying to OpenShift
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"

service:
  name: lab-service
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  name: lab-ingress
  host: "test.joeckr.dev" # add your own domain
  route: "false"  # Set to "true" to generate an OpenShift Route instead of Ingress
  className: "nginx"
  path: /
  pathType: "Prefix"
